import assert from "node:assert/strict";
import test from "node:test";
import { parseNetfactorPositionText } from "./netfactor-position-parser.ts";

test("parses NetFactor position rows and aggregates by account", () => {
  const text = [
    "Data Debenturista Qtde Vlr Compra Vlr Corrigido Vlr Rendimento Rentab.",
    "27/03/2025 - 1036 (234) CLIENTE TESTE 20 200.000,00 251.505,50 51.505,50 25,75 % 9.013,46 46.919,65 40.849,84 6.069,81 1.175,44 3.290,42 1,60 % % 204.585,87 196.747,84",
    "10/09/2021 - 396 (234) CLIENTE TESTE 13 130.000,00 398.197,96 268.197,96 206,31 % 40.229,69 0,00 0,00 0,00 0,00 8.295,03 2,14 % % 398.197,96 357.968,27"
  ].join("\n");

  const result = parseNetfactorPositionText(text);

  assert.equal(result.rows.length, 2);
  assert.equal(result.unmatchedDataLines.length, 0);
  assert.equal(result.accounts.length, 1);
  assert.equal(result.accounts[0]?.accountNumber, "234");
  assert.equal(result.accounts[0]?.totalQuantity, 33);
  assert.equal(result.accounts[0]?.totalCurrentNetValue, 554716.11);
});

test("parses grouped NetFactor rows generated by the robot PDF reader", () => {
  const text =
    "GROUPED (48) SELSON KUSSLER 226,0 2.260.000,00 9.638.057,76 7.378.057,76 331,97 % 1.106.708, 0,00 0,00 197.181,66 2,05 % 9.638.057,76";

  const result = parseNetfactorPositionText(text);

  assert.equal(result.rows.length, 1);
  assert.equal(result.accounts.length, 1);
  assert.equal(result.accounts[0]?.accountNumber, "48");
  assert.equal(result.accounts[0]?.debentureHolderName, "SELSON KUSSLER");
  assert.equal(result.accounts[0]?.totalQuantity, 226);
  assert.equal(result.accounts[0]?.totalCurrentNetValue, 9638057.76);
});
